# This is a generated config. Do not mess with it unless you know what you are doing!

author:
  name: ODPA
baseurl: /
description: A Portal for ODPA
markdown: GFM
collections:
  Participation:
    output: true
  Region:
    output: true
  AOS_AGROVOC_Concept_Server_fundation_ontology_model:
    output: true
  RTMSmapping:
    output: true
  RecurrentSituationSeries:
    output: true
  SimpleOrAggregated:
    output: true
  OOPMetrics:
    output: true
  GO_Top:
    output: true
  Controlflow:
    output: true
  Object_with_states:
    output: true
  VesselSpecies:
    output: true
  Objectrole:
    output: true
  DataTransformationPattern:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_Object_Property_ODP:
    output: true
  SpeciesConservation:
    output: true
  Computer_System:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Co-participation_ODP:
    output: true
  Classification:
    output: true
  PlanConditions:
    output: true
  SmartHome_Geometry:
    output: true
  Time_indexed_participation:
    output: true
  Musicalobject:
    output: true
  Invoice:
    output: true
  GearSpecies:
    output: true
  Collection:
    output: true
  Topic:
    output: true
  CommunicationEvent:
    output: true
  SpatioTemporalExtent:
    output: true
  Place:
    output: true
  Constituency:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_Equivalence_relation_between_Classes_ODP:
    output: true
  ClimaticZone:
    output: true
  Policy:
    output: true
  DescriptionAndSituation:
    output: true
  VesselWaterArea:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Multiple_Inheritance_ODP:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Object_Property_and_Universal_Restriction_ODPs:
    output: true
  TimeIndexedPartOf:
    output: true
  Observation:
    output: true
  HistoricalMap:
    output: true
  IntensionExtension:
    output: true
  Bag:
    output: true
  SmartHome_TimeInterval:
    output: true
  Airline:
    output: true
  CatchRecord:
    output: true
  ContextualizedWinstonPartWhole:
    output: true
  Description:
    output: true
  SmartHome_FeatureOfInterest:
    output: true
  Time_indexed_person_role:
    output: true
  GearWaterArea:
    output: true
  InformationObjectsAndRepresentationLanguages:
    output: true
  DigitalVideo:
    output: true
  CountingAs:
    output: true
  LCA_Pattern:
    output: true
  Scorepart:
    output: true
  PartOf:
    output: true
  Situation:
    output: true
  EventCore:
    output: true
  COP:
    output: true
  ConceptTerms:
    output: true
  ResourceAbundanceObservation:
    output: true
  AgentRole:
    output: true
  CollectionEntity:
    output: true
  TaskExecution:
    output: true
  Communities:
    output: true
  ResourceExploitationObservation:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Defined_Classes_and_SubclassOf_relation_ODPs:
    output: true
  PharmaInnova:
    output: true
  Literal_Reification:
    output: true
  Componency:
    output: true
  SmartHome_Sensing:
    output: true
  SmartHome_Object:
    output: true
  Price:
    output: true
  SpeciesHabitat:
    output: true
  AquaticResourceObservation:
    output: true
  SmartHome_Event:
    output: true
  LinnaeanTaxonomy:
    output: true
  Trajectory:
    output: true
  Action:
    output: true
  SmartHome_Network:
    output: true
  Standard_Enforcer_Pattern:
    output: true
  AffectedBy:
    output: true
  Role_task:
    output: true
  Vocabulary_Alignment_Pattern:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_Disjoint_Classes_ODP:
    output: true
  ActingFor:
    output: true
  Course:
    output: true
  Airline.owl:
    output: true
  ParticipantRole:
    output: true
  SpeciesConditions:
    output: true
  Reactor_pattern:
    output: true
  Experience_&_Observation:
    output: true
  Co-participation:
    output: true
  SmartHome_Property:
    output: true
  Notepattern:
    output: true
  GearVessel:
    output: true
  SmartHome_Situation:
    output: true
  Tagging:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_SubclassOf_relation,_Disjoint_Classes,_and_Exhaustive_Classes_ODPs:
    output: true
  Material_Transformation:
    output: true
  Set:
    output: true
  SpeciesEat:
    output: true
  Persons:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_Datatype_Property_ODP:
    output: true
  Nary_Participation:
    output: true
  PeriodicInterval:
    output: true
  Affordance:
    output: true
  Parameter:
    output: true
  TimeInterval:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Object_Property_or_Datatype_Property_or_Simple_Part-Whole_relation_ODPs:
    output: true
  TransportPattern:
    output: true
  WOP2012TestPatterns:
    output: true
  EthnicGroup:
    output: true
  Move:
    output: true
  SmartHome_Place:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Object-Role_ODP:
    output: true
  Sequence:
    output: true
  BasicPlanExecution:
    output: true
  SpeciesNames:
    output: true
  An_Ontology_Design_Pattern_for_Activity_Reasoning:
    output: true
  Transition:
    output: true
  Pollution:
    output: true
  AquaticResources:
    output: true
  BasicPlan:
    output: true
  WinstonPartWhole:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_Participation_ODP:
    output: true
  SpeciesBathymetry:
    output: true
  ? Lexico_Syntactic_ODPs_corresponding_to_Simple_Part-Whole_relation_%22or%22_Constituency_%22or%22_Componency_%22or%22_Collection-Entity_ODPs
  : output: true
  TimeIndexedClassification:
    output: true
  EventProcessing:
    output: true
  VerticalDistribution:
    output: true
  Biological_Entities:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_SubclassOf_%22or%22_Simple_Part-Whole_relation_ODPs:
    output: true
  Born_Digital_Archives:
    output: true
  Xsd:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_LocationODP:
    output: true
  List:
    output: true
  Lexico_Syntactic_ODP_corresponding_to_SubclassOf_relation_ODP:
    output: true
  Types_of_entities:
    output: true
  TimeIndexedSituation:
    output: true
  Lexico_Syntactic_ODPs_corresponding_to_Specified_Values_ODP:
    output: true
  NewsReportingEvent:
    output: true
excludes:
- public
- _layout
